"""empty message

Revision ID: 39100323a761
Revises: 946cbadef74c
Create Date: 2021-01-05 21:33:40.032966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39100323a761'
down_revision = '946cbadef74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
